import React, { useState } from "react";
import { SignalLog } from "../types";
import { 
  BookOpen, 
  CheckCircle2, 
  XCircle, 
  Clock, 
  TrendingUp, 
  TrendingDown, 
  Filter, 
  PieChart, 
  Award,
  AlertCircle
} from "lucide-react";

interface SignalJournalProps {
  signals: SignalLog[];
}

export const SignalJournal: React.FC<SignalJournalProps> = ({ signals }) => {
  const [filterOutcome, setFilterOutcome] = useState<string>("ALL");
  const [filterSetup, setFilterSetup] = useState<string>("ALL");

  const filtered = signals.filter((s) => {
    if (filterOutcome !== "ALL" && s.outcome !== filterOutcome) return false;
    if (filterSetup !== "ALL" && s.setupType !== filterSetup) return false;
    return true;
  });

  // Calculate High Confluence vs Low Confluence win rate
  const highConf = signals.filter((s) => s.confluenceScore >= 80);
  const highConfWins = highConf.filter((s) => s.outcome === "TARGET 1 HIT" || s.outcome === "TARGET 2 HIT").length;
  const highConfWinRate = highConf.length > 0 ? ((highConfWins / highConf.length) * 100).toFixed(1) : "0";

  const totalClosed = signals.filter((s) => s.outcome !== "ACTIVE").length;
  const totalWins = signals.filter((s) => s.outcome === "TARGET 1 HIT" || s.outcome === "TARGET 2 HIT").length;
  const overallWinRate = totalClosed > 0 ? ((totalWins / totalClosed) * 100).toFixed(1) : "0";

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="bg-[#0b0e14] p-4 rounded-xl border border-[#1b212f] flex flex-col sm:flex-row sm:items-center justify-between gap-3 font-mono text-xs">
        <div>
          <div className="flex items-center space-x-2 text-emerald-400 font-bold uppercase tracking-wider">
            <BookOpen className="w-4 h-4" />
            <span>CONFIRMED SIGNAL AUDIT JOURNAL</span>
          </div>
          <p className="text-zinc-400 font-sans text-xs mt-1">
            Every setup generated by TradeSynq is transparently recorded, tracking entry, stop loss, target hit, and statistical outcome.
          </p>
        </div>

        <div className="flex items-center space-x-3 shrink-0">
          <div className="bg-[#111622] p-2 rounded border border-[#1b2333] text-center">
            <span className="text-[10px] text-zinc-500 block">Overall Win Rate</span>
            <span className="text-base font-bold text-emerald-400">{overallWinRate}%</span>
          </div>
          <div className="bg-[#111622] p-2 rounded border border-emerald-500/30 text-center">
            <span className="text-[10px] text-emerald-400 block font-bold">80+ Confluence Win Rate</span>
            <span className="text-base font-bold text-emerald-300">{highConfWinRate}%</span>
          </div>
        </div>
      </div>

      {/* Filters Bar */}
      <div className="flex flex-wrap items-center gap-2 font-mono text-xs">
        <select
          value={filterOutcome}
          onChange={(e) => setFilterOutcome(e.target.value)}
          className="bg-[#111622] border border-[#1d2536] text-zinc-300 rounded-lg px-3 py-1.5 focus:outline-none"
        >
          <option value="ALL">All Outcomes</option>
          <option value="TARGET 1 HIT">Target 1 Hit</option>
          <option value="TARGET 2 HIT">Target 2 Hit</option>
          <option value="STOP LOSS HIT">Stop Loss Hit</option>
          <option value="ACTIVE">Active Signal</option>
        </select>

        <select
          value={filterSetup}
          onChange={(e) => setFilterSetup(e.target.value)}
          className="bg-[#111622] border border-[#1d2536] text-zinc-300 rounded-lg px-3 py-1.5 focus:outline-none"
        >
          <option value="ALL">All Strategy Types</option>
          <option value="Breakout Continuation">Breakout Continuation</option>
          <option value="Momentum Breakout">Momentum Breakout</option>
          <option value="Opening Range Breakout">Opening Range Breakout</option>
          <option value="VWAP Reclaim">VWAP Reclaim</option>
        </select>
      </div>

      {/* Signal Log Table */}
      <div className="bg-[#0b0e14] rounded-xl border border-[#1b212f] overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse font-mono text-xs">
            <thead>
              <tr className="border-b border-[#18202d] bg-[#090d13] text-[11px] uppercase text-zinc-400">
                <th className="py-2.5 px-3">Date / Time</th>
                <th className="py-2.5 px-3">Symbol</th>
                <th className="py-2.5 px-3">Setup</th>
                <th className="py-2.5 px-3">Score</th>
                <th className="py-2.5 px-3">Entry</th>
                <th className="py-2.5 px-3">Stop Loss</th>
                <th className="py-2.5 px-3">Exit Price</th>
                <th className="py-2.5 px-3">Outcome</th>
                <th className="py-2.5 px-3">Return %</th>
                <th className="py-2.5 px-3">Duration</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#141a24]">
              {filtered.map((log) => {
                const isWin = log.returnPercent && log.returnPercent > 0;
                const isStopped = log.outcome === "STOP LOSS HIT";
                const isActive = log.outcome === "ACTIVE";

                return (
                  <tr key={log.id} className="hover:bg-[#111722] transition-colors">
                    <td className="py-3 px-3 text-zinc-400">{log.dateTime}</td>
                    <td className="py-3 px-3 font-bold text-white">{log.symbol}</td>
                    <td className="py-3 px-3 text-zinc-300">{log.setupType}</td>
                    <td className="py-3 px-3">
                      <span className="px-1.5 py-0.5 rounded text-[10px] font-bold bg-zinc-800 text-emerald-400">
                        {log.confluenceScore}
                      </span>
                    </td>
                    <td className="py-3 px-3 text-zinc-300">₹{log.entryPrice}</td>
                    <td className="py-3 px-3 text-rose-400">₹{log.stopLoss}</td>
                    <td className="py-3 px-3 text-zinc-200">{log.exitPrice ? `₹${log.exitPrice}` : "-"}</td>
                    <td className="py-3 px-3">
                      <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                        isWin
                          ? "bg-emerald-500/20 text-emerald-300 border border-emerald-500/30"
                          : isStopped
                          ? "bg-rose-500/20 text-rose-300 border border-rose-500/30"
                          : "bg-sky-500/20 text-sky-300 border border-sky-500/30"
                      }`}>
                        {log.outcome}
                      </span>
                    </td>
                    <td className="py-3 px-3">
                      {log.returnPercent ? (
                        <span className={`font-bold ${isWin ? "text-emerald-400" : "text-rose-400"}`}>
                          {log.returnPercent > 0 ? "+" : ""}{log.returnPercent.toFixed(2)}%
                        </span>
                      ) : (
                        <span className="text-zinc-500">-</span>
                      )}
                    </td>
                    <td className="py-3 px-3 text-zinc-400">{log.holdingPeriod}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
